# Generated by Django 3.1.4 on 2021-01-03 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyExams', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grades',
            new_name='Grade',
        ),
    ]
