# Generated by Django 3.1.4 on 2021-01-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyExams', '0002_auto_20210103_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.TextField(choices=[('student', 'Student'), ('professor', 'Professor')], default='student'),
        ),
    ]
