# Generated by Django 3.1.4 on 2021-01-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyExams', '0003_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='examfile',
            field=models.FilePathField(default='exam_files/noexam.csv', path='MyExams/exam_files/'),
        ),
    ]
