# Generated by Django 3.1.4 on 2021-01-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyExams', '0004_exam_examfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='examfile',
            field=models.FilePathField(default='exam_files/noexam.csv'),
        ),
    ]
