# Generated by Django 3.1.4 on 2021-01-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyExams', '0005_auto_20210103_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='examfile',
            field=models.FileField(default='exam_files/noexam.csv', upload_to=''),
        ),
    ]
