# Generated by Django 3.1.4 on 2021-01-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyExams', '0006_auto_20210103_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='examfile',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='grade',
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_file',
            field=models.FileField(default='example_files/exam_files/noexam.csv', upload_to=''),
        ),
        migrations.AddField(
            model_name='grade',
            name='grade_file',
            field=models.FileField(default='example_files/exam_files/nograde.csv', upload_to=''),
        ),
    ]
