# Generated by Django 3.1.4 on 2021-01-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyExams', '0008_auto_20210103_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_file',
            field=models.FileField(upload_to=''),
        ),
    ]
