# Generated by Django 3.1.4 on 2021-01-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyExams', '0009_auto_20210104_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='location',
            field=models.CharField(max_length=40),
        ),
    ]
