# Generated by Django 3.1.4 on 2021-01-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyExams', '0010_auto_20210104_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_file',
            field=models.FileField(unique=True, upload_to=''),
        ),
    ]
