# Generated by Django 3.1.4 on 2021-01-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyExams', '0011_auto_20210104_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_file',
            field=models.FileField(unique=True, upload_to='exam_files/'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_file',
            field=models.FileField(upload_to='grade_files/'),
        ),
    ]
