# Generated by Django 3.1.4 on 2021-01-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyExams', '0012_auto_20210104_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='exam',
            name='time',
            field=models.TimeField(),
        ),
    ]
