# Generated by Django 3.1.4 on 2021-01-10 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=40)),
                ('exam_file', models.FileField(unique=True, upload_to='exam_files/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('role', models.TextField(choices=[('student', 'Student'), ('professor', 'Professor')], default='student')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_file', models.FileField(upload_to='grade_files/')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MyExams.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyExams.user')),
            ],
            options={
                'unique_together': {('exam', 'user')},
            },
        ),
    ]
